import { useState } from 'react'

const NextTravelTitle = () => {
  const categories = ['인기', '예술 및 문화', '야외', '산맥', '해변', '카테고리', '즐길 거리']
  const destinations = {
    인기: [
      { city: '캔모어', type: '샬레 숙소' },
      { city: '베날마데나', type: '아파트 숙소' },
      { city: '마르베야', type: '해변 근처 독채 숙소' },
      { city: '미하스', type: '휴가지 숙소' },
      { city: '프레스콧', type: '통나무집 숙소' },
      { city: '스캇츠데일', type: '휴가지 숙소' },
      { city: '투손', type: '대저택 숙소' },
      { city: '요스퍼', type: '휴가지 숙소' },
      { city: '마운틴뷰', type: '통나무집 숙소' },
      { city: 'Devonport', type: '휴가지 숙소' },
      { city: 'Mallacoota', type: '휴가지 숙소' },
      { city: '이비자', type: '휴가지 숙소' },
      { city: '애나하임', type: '아파트 숙소' },
      { city: '몬터레이', type: '독채 숙소' },
      { city: '파소 로블레스', type: '별장 숙소' },
      { city: '산타바바라', type: '별장 숙소' },
      { city: '소노마', type: '통나무집 숙소' },
      { city: 'La Serena', type: '휴가지 숙소' },
      { city: '두바이', type: '아파트 숙소' },
      { city: '버밍험', type: '휴가지 숙소' },
      { city: '브라이튼', type: '휴가지 숙소' },
      { city: '뷰드', type: '휴가지 숙소' },
      { city: '뉴캐슬 어폰 타인', type: '휴가지 숙소' },
      { city: 'Padstow', type: '별장 숙소' },
      { city: 'South West England', type: '독채 숙소' },
      { city: 'Whitby', type: '별장 숙소' },
      { city: 'Fort Myers', type: '해변 근처 독채 숙소' },
      { city: '잭슨빌', type: '반려동물 동반이 허용되는 숙소' },
      { city: '키시미', type: '별장 숙소' },
      { city: '롱보트 키', type: '독채 숙소' },
      { city: '올랜도', type: '독채 숙소' },
      { city: '상트페테르부르크', type: '휴가지 숙소' },
      { city: '세인트 오거스틴', type: '해변 바로 앞 숙소' },
      { city: '더 빌리지스', type: '반려동물 동반이 허용되는 숙소' },
      { city: 'Dahlonega', type: '휴가지 숙소' },
      { city: '크레타', type: '별장 숙소' },
      { city: '미코노스', type: '콘도 숙소' },
      { city: '산토리니', type: '대저택 숙소' },
      { city: '오아후', type: '해변 근처 독채 숙소' },
      { city: 'Capri', type: '독채 숙소' },
      { city: 'Bar Harbor', type: '반려동물 동반이 허용되는 숙소' },
      { city: 'Mackinac Island', type: '호숫가 주택 숙소' },
      { city: 'St. Joseph', type: '독채 숙소' },
      { city: 'Larsmont', type: '휴가지 숙소' },
      { city: '라스베이거스', type: '휴가지 숙소' },
      { city: 'Madrid', type: '휴가지 숙소' },
      { city: '산타페', type: '아파트 숙소' },
      { city: 'Bermagui', type: '반려동물 동반이 허용되는 숙소' },
      { city: 'Evans Head', type: '휴가지 숙소' },
      { city: '소텔', type: '해변 근처 독채 숙소' },
      { city: 'Young', type: '휴가지 숙소' },
      { city: 'Ocracoke', type: '독채 숙소' },
      { city: '피렌체', type: '콘도 숙소' },
      { city: '레이크사이드', type: '휴가지 숙소' },
      { city: '링컨 시티', type: '휴가지 숙소' },
      { city: '파포스', type: '휴가지 숙소' },
      { city: '말레니', type: '휴가지 숙소' },
      { city: 'Stanthorpe', type: '반려동물 동반이 허용되는 숙소' },
      { city: '뉴포트', type: '대저택 숙소' },
      { city: '글래스고', type: '통나무집 숙소' },
      { city: 'Scottish Highlands', type: '휴가지 숙소' },
      { city: 'St Andrews', type: '해변 바로 앞 숙소' },
      { city: 'McLaren Vale', type: '휴가지 숙소' },
      { city: 'Wallaroo', type: '해변 바로 앞 숙소' },
      { city: '찰스턴', type: '아파트 숙소' },
      { city: 'Hvar', type: '독채 숙소' },
      { city: 'Saint John', type: '휴가지 숙소' },
      { city: '채터누가', type: '휴가지 숙소' },
      { city: 'Concan', type: '수영장이 있는 숙소' },
      { city: 'Fredericksburg', type: '독채 숙소' },
      { city: '뉴브라운펠스', type: '콘도 숙소' },
      { city: '락포트', type: '해변 바로 앞 숙소' },
      { city: '웨이코', type: '독채 숙소' },
      { city: 'Forest of Dean District', type: '휴가지 숙소' },
      { city: '저지', type: '휴가지 숙소' },
      { city: '라임 레지스', type: '별장 숙소' },
      { city: '맨체스터', type: '독채 숙소' },
      { city: 'Seaview', type: '휴가지 숙소' },
      { city: 'Southwold', type: '휴가지 숙소' },
      { city: 'Staithes', type: '휴가지 숙소' },
      { city: 'Wells-next-the-Sea', type: '휴가지 숙소' },
      { city: '세인트 조지', type: '아파트 숙소' },
      { city: '베니돔', type: '휴가지 숙소' },
      { city: '바원헤즈', type: '반려동물 동반이 허용되는 숙소' },
      { city: '캐슬메인', type: '휴가지 숙소' },
      { city: '힐스빌', type: '별장 숙소' },
      { city: 'Marysville', type: '별장 숙소' },
      { city: '소렌토', type: '해변 근처 독채 숙소' },
      { city: 'Chincoteague', type: '해변 근처 독채 숙소' },
      { city: '윌리엄스버그', type: '휴가지 숙소' },
      { city: '헤이 온 와이', type: '별장 숙소' },
      { city: 'Llandudno', type: '독채 숙소' },
      { city: '텐비', type: '휴가지 숙소' },
    ],
    '예술 및 문화': [
      { city: '피닉스', type: '수영장이 있는 숙소' },
      { city: '핫스프링스', type: '호숫가 주택 숙소' },
      { city: '로스앤젤레스', type: '별장 숙소' },
      { city: '샌디에이고', type: '해변 근처 콘도 숙소' },
      { city: '샌프란시스코', type: '휴가지 숙소' },
      { city: '바르셀로나', type: '휴가지 숙소' },
      { city: '프라하', type: '휴가지 숙소' },
      { city: '워싱턴', type: '반려동물 동반이 허용되는 숙소' },
      { city: '케직', type: '휴가지 숙소' },
      { city: '런던', type: '휴가지 숙소' },
      { city: '스카버러', type: '휴가지 숙소' },
      { city: 'Sherwood Forest', type: '별장 숙소' },
      { city: 'York', type: '독채 숙소' },
      { city: '파리', type: '콘도 숙소' },
      { city: '로즈', type: '아파트 숙소' },
      { city: '내쉬빌', type: '휴가지 숙소' },
      { city: '더블린', type: '별장 숙소' },
      { city: '피렌체', type: '독채 숙소' },
      { city: '로마', type: '콘도 숙소' },
      { city: '리스본', type: '해변 바로 앞 숙소' },
      { city: 'Grand Isle', type: '휴가지 숙소' },
      { city: '뉴올리언스', type: '휴가지 숙소' },
      { city: '마사스 빈야드', type: '휴가지 숙소' },
      { city: '사우스 헤이븐', type: '콘도 숙소' },
      { city: '덜루스', type: '반려동물 동반이 허용되는 숙소' },
      { city: '암스테르담', type: '아파트 숙소' },
      { city: '뉴욕', type: '휴가지 숙소' },
      { city: '니스', type: '독채 숙소' },
      { city: 'Inverness', type: '샬레 숙소' },
      { city: '말라가', type: '휴가지 숙소' },
      { city: '발렌시아', type: '샬레 숙소' },
      { city: '스플리트', type: '저택 숙소' },
      { city: '내쉬빌', type: '휴가지 숙소' },
      { city: '오스틴', type: '수영장이 있는 숙소' },
      { city: '휴스턴', type: '휴가지 숙소' },
      { city: '다트머스', type: '독채 숙소' },
      { city: 'Edinburgh', type: '휴가지 숙소' },
      { city: '리버풀', type: '휴가지 숙소' },
      { city: '세인트 아이브스', type: '독채 숙소' },
      { city: 'Lake Powell', type: '휴가지 숙소' },
      { city: '레이크 안나', type: '반려동물 동반이 허용되는 숙소' },
      { city: '레븐워스', type: '통나무집 숙소' },
      { city: '시애틀', type: '휴가지 숙소' },
    ],
    야외: [
      { city: 'Lake Martin', type: '아파트 숙소' },
      { city: 'Banff', type: '아파트 숙소' },
      { city: '네르하', type: '아파트 숙소' },
      { city: 'Greer', type: '통나무집 숙소' },
      { city: '레이크하바수 시티', type: '콘도 숙소' },
      { city: 'Lake Powell', type: '휴가지 숙소' },
      { city: 'North Rim', type: '휴가지 숙소' },
      { city: 'Payson', type: '휴가지 숙소' },
      { city: '파인톱-레이크 사이드', type: '휴가지 숙소' },
      { city: 'Red Rock', type: '휴가지 숙소' },
      { city: 'Dinner Plain', type: '휴가지 숙소' },
      { city: 'Streaky Bay', type: '휴가지 숙소' },
      { city: 'Emerald Lake', type: '휴가지 숙소' },
      { city: '밴쿠버 아일랜드', type: '반려동물 동반이 허용되는 숙소' },
      { city: '빅토리아', type: '저택 숙소' },
      { city: 'Idyllwild-Pine Cove', type: '통나무집 숙소' },
      { city: '매머드 레이크', type: '휴가지 숙소' },
      { city: '팜데저트', type: '아파트 숙소' },
      { city: 'Shaver Lake', type: '휴가지 숙소' },
      { city: '사우스 레이크 타호', type: '휴가지 숙소' },
      { city: 'Cultus Lake', type: '휴가지 숙소' },
      { city: 'Georgian Bay', type: '휴가지 숙소' },
      { city: 'Manitoulin Island', type: '휴가지 숙소' },
      { city: 'Ottawa River', type: '별장 숙소' },
      { city: 'The Blue Mountains', type: '휴가지 숙소' },
      { city: '웨스트 켈로우나', type: '휴가지 숙소' },
      { city: '그란 카나리아', type: '독채 숙소' },
      { city: '란자로테', type: '가족여행에 적합한 숙소' },
      { city: 'Castle Hill', type: '휴가지 숙소' },
      { city: '아스펜', type: '스키 타고 출입 가능한 숙소' },
      { city: '콜로라도 스프링스', type: '휴가지 숙소' },
      { city: '덴버', type: '휴가지 숙소' },
      { city: 'Durango', type: '반려동물 동반이 허용되는 숙소' },
      { city: '에스테스 파크', type: '아파트 숙소' },
      { city: 'Grand Lake', type: '휴가지 숙소' },
      { city: 'Keystone', type: '콘도 숙소' },
      { city: '베일', type: '휴가지 숙소' },
      { city: '윈터파크', type: '통나무집 숙소' },
      { city: 'Salcombe', type: '휴가지 숙소' },
      { city: '스워니지', type: '독채 숙소' },
      { city: '케이프 코랄', type: '휴가지 숙소' },
      { city: 'Blue Ridge', type: '통나무집 숙소' },
      { city: 'Jekyll Island', type: '해변 바로 앞 숙소' },
      { city: 'Lake Lanier', type: '반려동물 동반이 허용되는 숙소' },
      { city: 'Corfu', type: '휴가지 숙소' },
      { city: '맥콜', type: '통나무집 숙소' },
      { city: 'Clear Lake', type: '콘도 숙소' },
      { city: 'Lough Eske', type: '휴가지 숙소' },
      { city: 'Lake Cumberland', type: '통나무집 숙소' },
      { city: '포틀랜드', type: '반려동물 동반이 허용되는 숙소' },
      { city: '사우스 포트랜드', type: '휴가지 숙소' },
      { city: '딥 크릭 호수', type: '수영장이 있는 숙소' },
      { city: 'Lake Michigan Beach', type: '해변 근처 독채 숙소' },
      { city: '레이크사이드', type: '휴가지 숙소' },
      { city: 'Torch Lake', type: '호숫가 주택 숙소' },
      { city: '트래버스 시티', type: '콘도 숙소' },
      { city: 'Upper Peninsula of Michigan', type: '휴가지 숙소' },
      { city: '브랜슨', type: '독채 숙소' },
      { city: '오자크스 호', type: '휴가지 숙소' },
      { city: '빅스카이', type: '휴가지 숙소' },
      { city: '웨스트 옐로스톤', type: '콘도 숙소' },
      { city: 'Mount Charleston', type: '휴가지 숙소' },
      { city: 'Cloudcroft', type: '통나무집 숙소' },
      { city: 'Red River', type: '독채 숙소' },
      { city: '벨링겐', type: '반려동물 동반이 허용되는 숙소' },
      { city: '브런즈윅 헤즈', type: '반려동물 동반이 허용되는 숙소' },
      { city: '애디론댁 산맥', type: '휴가지 숙소' },
      { city: 'Lake Placid', type: '콘도 숙소' },
      { city: '나이아가라 폭포', type: '아파트 숙소' },
      { city: 'Bald Head Island', type: '별장 숙소' },
      { city: '브라이슨 시티', type: '콘도 숙소' },
      { city: 'Emerald Isle', type: '휴가지 숙소' },
      { city: 'Lake Gaston', type: '휴가지 숙소' },
      { city: '레이크 루어', type: '휴가지 숙소' },
      { city: 'Lake Norman of Catawba', type: '휴가지 숙소' },
      { city: 'Mount Airy', type: '통나무집 숙소' },
      { city: '오크 섬', type: '반려동물 동반이 허용되는 숙소' },
      { city: 'Geneva-on-the-Lake', type: '휴가지 숙소' },
      { city: 'Medicine Park', type: '휴가지 숙소' },
      { city: 'Turner Falls', type: '통나무집 숙소' },
      { city: 'Muskoka Lakes', type: '휴가지 숙소' },
      { city: 'Tobermory', type: '독채 숙소' },
      { city: '벤드', type: '별장 숙소' },
      { city: 'Crater Lake', type: '호숫가 주택 숙소' },
      { city: 'Northern Oregon Coast Range', type: '휴가지 숙소' },
      { city: 'Sunriver', type: '휴가지 숙소' },
      { city: '레이크 하모니', type: '휴가지 숙소' },
      { city: 'Mount Pocono', type: '휴가지 숙소' },
      { city: 'Mont-Tremblant', type: '통나무집 숙소' },
      { city: 'Aviemore', type: '휴가지 숙소' },
      { city: 'Isle of Mull', type: '별장 숙소' },
      { city: '로브', type: '휴가지 숙소' },
      { city: 'Mountain Rest', type: '통나무집 숙소' },
      { city: 'St Helens', type: '휴가지 숙소' },
      { city: '미국', type: '휴가지 숙소' },
      { city: '캐년 레이크', type: '휴가지 숙소' },
      { city: 'Lake Austin', type: '휴가지 숙소' },
      { city: 'Lake Buchanan', type: '휴가지 숙소' },
      { city: 'Betws-y-Coed', type: '휴가지 숙소' },
      { city: 'Filey', type: '해변 바로 앞 숙소' },
      { city: 'Fort William', type: '샬레 숙소' },
      { city: '로몬드 호', type: '휴가지 숙소' },
      { city: 'Port Isaac', type: '아파트 숙소' },
      { city: '모아브', type: '별장 숙소' },
      { city: 'Mount Zion', type: '휴가지 숙소' },
      { city: 'Moraira', type: '휴가지 숙소' },
      { city: '인버로크', type: '휴가지 숙소' },
      { city: 'Metung', type: '휴가지 숙소' },
      { city: 'Mount Buller', type: '휴가지 숙소' },
      { city: '포트 캠벨', type: '별장 숙소' },
      { city: 'Wilsons Promontory', type: '휴가지 숙소' },
      { city: 'Shenandoah', type: '별장 숙소' },
      { city: '스미스 마운틴호', type: '휴가지 숙소' },
      { city: 'Snowdon', type: '별장 숙소' },
      { city: '첼랜호', type: '휴가지 숙소' },
      { city: 'Lake Crescent', type: '휴가지 숙소' },
      { city: 'Lake Quinault', type: '휴가지 숙소' },
      { city: 'Quinault', type: '휴가지 숙소' },
      { city: 'Skamania', type: '휴가지 숙소' },
      { city: '스노우슈', type: '휴가지 숙소' },
      { city: '제네바 호수', type: '수영장이 있는 숙소' },
      { city: '위스콘신 델스', type: '휴가지 숙소' },
      { city: '미국', type: '휴가지 숙소' },
    ],

    산맥: [
      { city: 'Mentone', type: '통나무집 숙소' },
      { city: 'Sedona', type: '반려동물 동반이 허용되는 숙소' },
      { city: 'Helen', type: '샬레 숙소' },
      { city: 'Pine Mountain', type: '휴가지 숙소' },
      { city: '스톤 마운틴', type: '통나무집 숙소' },
      { city: 'Island Park', type: '아파트 숙소' },
      { city: 'Blue Mountains', type: '통나무집 숙소' },
      { city: '애쉬빌', type: '수영장이 있는 숙소' },
      { city: 'Blowing Rock', type: '휴가지 숙소' },
      { city: 'Boone', type: '휴가지 숙소' },
      { city: 'Hochatown', type: '휴가지 숙소' },
      { city: 'Pigeon Forge', type: '휴가지 숙소' },
      { city: 'Townsend', type: '휴가지 숙소' },
      { city: 'Wears Valley', type: '휴가지 숙소' },
      { city: 'Cabins', type: '휴가지 숙소' },
    ],
    해변: [
      { city: 'Dauphin Island', type: '저택 숙소' },
      { city: 'Fort Morgan', type: '휴가지 숙소' },
      { city: '걸프 쇼어즈', type: '휴가지 숙소' },
      { city: '브루니섬', type: '휴가지 숙소' },
      { city: 'Crescent Head', type: '휴가지 숙소' },
      { city: 'Gerringong', type: '휴가지 숙소' },
      { city: '해밀턴 섬', type: '독채 숙소' },
      { city: '란셀린', type: '휴가지 숙소' },
      { city: '멜버른 비치', type: '휴가지 숙소' },
      { city: 'Moonta Bay', type: '휴가지 숙소' },
      { city: '오션 그로브', type: '휴가지 숙소' },
      { city: '마요르카', type: '별장 숙소' },
      { city: 'Big Sur', type: '해변 근처 독채 숙소' },
      { city: '보데가 베이', type: '휴가지 숙소' },
      { city: '캠브리아', type: '독채 숙소' },
      { city: '카유코스', type: '휴가지 숙소' },
      { city: '헌팅턴 비치', type: '아파트 숙소' },
      { city: 'la Jolla Shores Beach', type: '휴가지 숙소' },
      { city: '라구나 비치', type: '별장 숙소' },
      { city: '롱비치', type: '독채 숙소' },
      { city: '말리부', type: '방갈로 숙소' },
      { city: 'Mission Beach', type: '휴가지 숙소' },
      { city: '뉴포트 비치', type: '아파트 숙소' },
      { city: '오션사이드', type: '휴가지 숙소' },
      { city: '팜스프링스', type: '저택 숙소' },
      { city: '피스모 비치', type: '독채 숙소' },
      { city: '산타크루즈', type: '콘도 숙소' },
      { city: '샌타모니카', type: '해변 근처 콘도 숙소' },
      { city: 'Sea Ranch', type: '반려동물 동반이 허용되는 숙소' },
      { city: 'Playa Blanca', type: '휴가지 숙소' },
      { city: '푸에르트벤츄라', type: '휴가지 숙소' },
      { city: '푸에르토 델 카르멘', type: '저택 숙소' },
      { city: '테네리페', type: '반려동물 동반이 허용되는 숙소' },
      { city: '아이아 나파', type: '아파트 숙소' },
      { city: '베서니 비치', type: '휴가지 숙소' },
      { city: 'Dewey Beach', type: '독채 숙소' },
      { city: 'Blackpool', type: '휴가지 숙소' },
      { city: 'Isle of Wight', type: '샬레 숙소' },
      { city: '뉴키', type: '휴가지 숙소' },
      { city: '웨이머스', type: '별장 숙소' },
      { city: '알부페이라', type: '해변 바로 앞 숙소' },
      { city: 'Alys Beach', type: '휴가지 숙소' },
      { city: '안나 마리아 아일랜드', type: '휴가지 숙소' },
      { city: 'Boca Grande', type: '휴가지 숙소' },
      { city: '브레이든턴', type: '독채 숙소' },
      { city: 'Cape San Blas', type: '해변 근처 독채 숙소' },
      { city: '캡티바', type: '휴가지 숙소' },
      { city: 'Clearwater Beach', type: '아파트 숙소' },
      { city: '코코아 비치', type: '아파트 숙소' },
      { city: 'Daytona Beach', type: '독채 숙소' },
      { city: '데스틴', type: '해변 근처 독채 숙소' },
      { city: '잉글우드', type: '독채 숙소' },
      { city: '포트 로더데일', type: '별장 숙소' },
      { city: 'Fort Myers Beach', type: '휴가지 숙소' },
      { city: '포트 와튼 비치', type: '해변 근처 콘도 숙소' },
      { city: 'Grayton Beach', type: '해변 근처 독채 숙소' },
      { city: 'Gulf of Mexico', type: '휴가지 숙소' },
      { city: '인디언 록스 비치', type: '반려동물 동반이 허용되는 숙소' },
      { city: '이슬라모라다', type: '해변 근처 콘도 숙소' },
      { city: '잭슨빌 비치', type: '해변 바로 앞 숙소' },
      { city: 'Key Largo', type: '독채 숙소' },
      { city: '마데이라 비치', type: '콘도 숙소' },
      { city: '마라톤', type: '콘도 숙소' },
      { city: 'Marco Island', type: '아파트 숙소' },
      { city: 'Mexico Beach', type: '해변 바로 앞 숙소' },
      { city: '마이애미 비치', type: '휴가지 숙소' },
      { city: '마이애미', type: '휴가지 숙소' },
      { city: '미라마르 비치', type: '독채 숙소' },
      { city: '네이플스', type: '휴가지 숙소' },
      { city: 'Navarre Beach', type: '휴가지 숙소' },
      { city: '뉴스머나비치', type: '콘도 숙소' },
      { city: 'Okaloosa Island', type: '아파트 숙소' },
      { city: 'Panama City Beach', type: '휴가지 숙소' },
      { city: '펜사콜라 비치', type: '별장 숙소' },
      { city: 'Perdido Key', type: '휴가지 숙소' },
      { city: 'Rosemary Beach', type: '휴가지 숙소' },
      { city: 'Saint George Island', type: '휴가지 숙소' },
      { city: '산타 로사 비치', type: '휴가지 숙소' },
      { city: '새러소타', type: '별장 숙소' },
      { city: 'Seagrove Beach', type: '휴가지 숙소' },
      { city: 'Seaside', type: '해변 근처 독채 숙소' },
      { city: 'South Beach', type: '독채 숙소' },
      { city: 'St. Augustine Beach', type: '콘도 숙소' },
      { city: 'St. Pete Beach', type: '휴가지 숙소' },
      { city: '탬파', type: '대저택 숙소' },
      { city: '웨스트 팜 비치', type: '아파트 숙소' },
      { city: 'Bora-Bora', type: '휴가지 숙소' },
      { city: '타이비 아일랜드', type: '독채 숙소' },
      { city: '호놀룰루', type: '해변 근처 독채 숙소' },
      { city: '카일루아-코나', type: '휴가지 숙소' },
      { city: 'Kapalua', type: '아파트 숙소' },
      { city: '카우이', type: '별장 숙소' },
      { city: '키헤이', type: '해변 근처 독채 숙소' },
      { city: 'Ko Olina Beach', type: '휴가지 숙소' },
      { city: '마우이', type: '콘도 숙소' },
      { city: 'Topsail Island', type: '휴가지 숙소' },
      { city: '올드 오차드 비치', type: '콘도 숙소' },
      { city: 'Wells', type: '휴가지 숙소' },
      { city: '케이프 카드', type: '아파트 숙소' },
      { city: 'Nantucket', type: '휴가지 숙소' },
      { city: '비록시', type: '해변 근처 콘도 숙소' },
      { city: '아발론', type: '휴가지 숙소' },
      { city: 'Jersey Shore', type: '해변 근처 독채 숙소' },
      { city: 'North Wildwood', type: '반려동물 동반이 허용되는 숙소' },
      { city: '오션 씨티', type: '독채 숙소' },
      { city: 'Sea Isle City', type: '휴가지 숙소' },
      { city: 'Stone Harbor', type: '수영장이 있는 숙소' },
      { city: 'Hyams Beach', type: '휴가지 숙소' },
      { city: '파이어 아일랜드', type: '휴가지 숙소' },
      { city: 'Montauk', type: '독채 숙소' },
      { city: 'Ocean Beach', type: '독채 숙소' },
      { city: '애틀란틱 비치', type: '독채 숙소' },
      { city: '캐롤리나 비치', type: '휴가지 숙소' },
      { city: 'Corolla', type: '해변 근처 독채 숙소' },
      { city: 'Holden Beach', type: '반려동물 동반이 허용되는 숙소' },
      { city: '키티호크', type: '휴가지 숙소' },
      { city: 'Kure Beach', type: '해변 근처 독채 숙소' },
      { city: '낵스 헤드', type: '휴가지 숙소' },
      { city: 'Ocean Isle Beach', type: '수영장이 있는 숙소' },
      { city: 'Sunset Beach', type: '해변 바로 앞 숙소' },
      { city: '서프 시티', type: '휴가지 숙소' },
      { city: '윌밍턴', type: '해변 근처 독채 숙소' },
      { city: 'Wrightsville Beach', type: '해변 근처 독채 숙소' },
      { city: 'Sauble Beach', type: '휴가지 숙소' },
      { city: 'Wasaga Beach', type: '휴가지 숙소' },
      { city: '캐논 비치', type: '휴가지 숙소' },
      { city: 'Seaside', type: '독채 숙소' },
      { city: 'Carvoeiro', type: '아파트 숙소' },
      { city: '골드 코스트', type: '휴가지 숙소' },
      { city: '모레턴 섬', type: '휴가지 숙소' },
      { city: 'Block Island', type: '휴가지 숙소' },
      { city: 'Puerto Peñasco', type: '휴가지 숙소' },
      { city: 'Charleston Oceanfront Villas', type: '휴가지 숙소' },
      { city: 'Edisto Beach', type: '휴가지 숙소' },
      { city: '폴리 비치', type: '독채 숙소' },
      { city: 'Fripp Island', type: '휴가지 숙소' },
      { city: '아일 오브 팜스', type: '해변 바로 앞 숙소' },
      { city: 'Kiawah Island', type: '콘도 숙소' },
      { city: '머틀 비치', type: '휴가지 숙소' },
      { city: '폴리스 아일랜드', type: '휴가지 숙소' },
      { city: 'Seabrook Island', type: '휴가지 숙소' },
      { city: "Sullivan's Island", type: '휴가지 숙소' },
      { city: '서프사이드 비치', type: '휴가지 숙소' },
      { city: '알리칸테', type: '휴가지 숙소' },
      { city: 'Costa Adeje', type: '아파트 숙소' },
      { city: 'Costa del Sol Occidental', type: '휴가지 숙소' },
      { city: '푸엥히롤라', type: '휴가지 숙소' },
      { city: '로스 크리스티아노', type: '해변 근처 독채 숙소' },
      { city: 'Corpus Christi', type: '휴가지 숙소' },
      { city: '포트 애런사스', type: '휴가지 숙소' },
      { city: '사우스 파드레 섬', type: '해변 근처 독채 숙소' },
      { city: '서프사이드 비치', type: '해변 바로 앞 숙소' },
      { city: 'Bournemouth', type: '통나무집 숙소' },
      { city: 'New Quay', type: '휴가지 숙소' },
      { city: '앵글씨', type: '휴가지 숙소' },
      { city: 'Abersoch', type: '반려동물 동반이 허용되는 숙소' },
      { city: 'Seabrook', type: '휴가지 숙소' },
      { city: 'Jurien Bay', type: '반려동물 동반이 허용되는 숙소' },
    ],
    카테고리: [
      { city: '멋진 수영장' },
      { city: '북극' },
      { city: '캠핑장' },
      { city: '캠핑카' },
      { city: '캐슬' },
      { city: '컨테이너하우스' },
      { city: '한적한 시골' },
      { city: '디자인' },
      { city: '복토 주택' },
      { city: '농장' },
      { city: '국립공원' },
      { city: '와인 농장' },
      { city: '기상천외한 숙소' },
      { city: '초소형 주택' },
      { city: '타워' },
      { city: '풍차' },
      { city: 'Luxe' },
    ],
    '즐길 거리': [
      { city: '런던', type: '잉글랜드' },
      { city: '파리', type: '일드프랑스' },
      { city: '뉴욕', type: '뉴욕' },
      { city: '바르셀로나', type: '카탈루냐' },
      { city: '이스탄불', type: '이스탄불' },
      { city: '발리', type: '인도네시아' },
      { city: '암스테르담', type: 'North Holland' },
      { city: '마이애미', type: '플로리다' },
      { city: '마드리드', type: '마드리드의 커뮤니티' },
      { city: '로스앤젤레스', type: '캘리포니아' },
      { city: '로마', type: 'Lazio' },
      { city: '리스본', type: '리스본' },
      { city: '도쿄', type: '도쿄' },
      { city: '빈', type: 'Vienna' },
      { city: '아테네', type: '그리스' },
      { city: '프라하', type: '체코' },
      { city: '올랜도', type: '플로리다' },
      { city: '칸쿤', type: 'Quintana Roo' },
      { city: '산토리니', type: '그리스' },
      { city: '멕시코시티', type: 'Mexico City' },
      { city: '베니스', type: 'Veneto' },
      { city: '플라야 델 카르멘', type: 'Quintana Roo' },
      { city: '샌프란시스코', type: '캘리포니아' },
      { city: '라스베이거스', type: '네바다' },
      { city: '보스턴', type: '매사추세츠' },
      { city: '샌디에이고', type: '캘리포니아' },
      { city: '시카고', type: '일리노이' },
      { city: '시애틀', type: '워싱턴' },
      { city: '워싱턴', type: '워싱턴' },
      { city: '애틀랜타', type: '조지아' },
      { city: '오스틴', type: '텍사스' },
      { city: '마우이', type: '하와이' },
      { city: '뉴올리언스', type: '루이지애나' },
      { city: '산후안', type: '산후안' },
      { city: '오아후', type: '하와이' },
      { city: '덴버', type: '콜로라도' },
      { city: '내쉬빌', type: '테네시' },
      { city: '찰스턴', type: '사우스캐롤라이나' },
      { city: '사바나', type: '조지아' },
      { city: '두바이', type: '두바이' },
      { city: '서울', type: '서울' },
      { city: '프랑스' },
      { city: '베를린', type: '베를린' },
      { city: '캐나다' },
      { city: 'Toronto', type: '온타리오' },
      { city: '스위스' },
      { city: '부다페스트', type: '헝가리' },
      { city: '스페인' },
      { city: '포르투갈' },
      { city: '미국' },
      { city: '이탈리아' },
      { city: '그리스' },
      { city: '크로아티아' },
      { city: '밴쿠버', type: '브리티쉬 컬럼비아' },
      { city: '멕시코' },
      { city: '더블린', type: 'County Dublin' },
      { city: '독일' },
      { city: '코스타리카' },
      { city: '맨해튼', type: '뉴욕' },
      { city: '일본' },
      { city: '코펜하겐', type: '덴마크' },
      { city: '몬트리올', type: '퀘벡' },
      { city: '브뤼셀', type: '브뤼셀' },
      { city: '발렌시아', type: 'Valencian Community' },
      { city: '싱가포르' },
      { city: '니스', type: "Provence-Alpes-Côte d'Azur" },
      { city: '뮌헨', type: '바바리아' },
      { city: '마요르카', type: '발레아레스 제도' },
      { city: '태국' },
      { city: '툴룸', type: 'Quintana Roo' },
      { city: '아일랜드' },
      { city: '포르투', type: 'Porto District' },
      { city: '잉글랜드', type: '영국' },
      { city: '마이애미 비치', type: '플로리다' },
      { city: '테네리페', type: 'Canary Islands' },
      { city: '네덜란드' },
      { city: '취리히', type: '취리히' },
      { city: '사이프러스' },
      { city: '스톡홀름', type: 'Stockholm County' },
      { city: '케이프타운', type: '웨스턴케이프 주' },
      { city: '노르웨이' },
      { city: '시드니', type: '뉴사우스웨일스' },
      { city: '토스카나', type: '이탈리아' },
      { city: '미코노스', type: '그리스' },
      { city: '하와이', type: '미국' },
      { city: '피렌체', type: '토스카나' },
      { city: '콜롬비아' },
      { city: '키이우', type: '우크라이나' },
      { city: '안탈리아', type: 'Antalya' },
      { city: '아이슬란드' },
      { city: '방콕', type: '태국' },
      { city: '부에노스 아이레스', type: 'Buenos Aires' },
      { city: '보고타', type: '보고타' },
      { city: '바르샤바', type: '마조프셰 주' },
    ],
  }

  const [selectedCategory, setSelectedCategory] = useState('인기')
  const [showAllDestinations, setShowAllDestinations] = useState(false)

  return (
    <section className='bg-gray-100 text-gray-700 py-8 px-2 sm:px-6 lg:px-8'>
      <div className=' mx-auto px-4 sm:px-6 lg:px-8'>
        <h2 className='text-2xl font-bold mb-6'>다음 여행을 위한 추천 여행지</h2>

        <div className='flex space-x-4 '>
          {categories.map(category => (
            <button
              key={category}
              className={`text-gray-700 hover:text-gray-900 ${
                selectedCategory === category ? ' pb-4 border-b-2 border-black relative' : 'pb-4'
              }`}
              onClick={() => setSelectedCategory(category)}
            >
              {category}
            </button>
          ))}
        </div>
        <hr className='border-gray-300 mb-6 pb-4  ' />
        <div className='grid grid-cols-2 md:grid-cols-4 lg:grid-cols-6 gap-4'>
          {/* 변경된 부분 */}
          {destinations[selectedCategory]
            .slice(0, showAllDestinations ? destinations[selectedCategory].length : 17)
            .map((destination, index) => (
              <div key={index}>
                <h3 className='font-semibold'>{destination.city}</h3>

                <p className='text-gray-500 font-normal'>{destination.type}</p>
              </div>
            ))}
          {!showAllDestinations && (
            <div className='mt-4'>
              <button
                className='text-gray-700 hover:text-gray-900'
                onClick={() => setShowAllDestinations(true)}
              >
                더 보기 ▼
              </button>
            </div>
          )}
        </div>
        {/* 변경된 부분 */}
      </div>
      <hr className='border-gray-300 mb-2 mt-10' />
    </section>
  )
}

export default NextTravelTitle
